import type { Category } from "@/types/content";

export const categories: Category[] = [
  {
    id: "accounts-passwords",
    slug: "accounts-passwords",
    label: "Accounts & Passwords",
    shortDescription: "Sign-in trouble, password resets, and account recovery.",
    icon: "keyRound",
    order: 1,
    featured: true,
    emergencyRelevant: true,
    searchAliases: ["password", "sign in", "account", "locked out"],
  },
  {
    id: "phone-problems",
    slug: "phone-problems",
    label: "Phone Problems",
    shortDescription: "Storage, charging, and everyday phone trouble.",
    icon: "smartphone",
    order: 2,
    featured: true,
    emergencyRelevant: true,
    searchAliases: ["phone", "mobile", "android", "iphone"],
  },
  {
    id: "laptop-basics",
    slug: "laptop-basics",
    label: "Laptop Basics",
    shortDescription: "Simple laptop tasks and first-step troubleshooting.",
    icon: "laptop",
    order: 3,
    featured: true,
    emergencyRelevant: false,
    searchAliases: ["computer", "laptop", "pc"],
  },
  {
    id: "wifi-internet",
    slug: "wifi-internet",
    label: "Wi-Fi & Internet",
    shortDescription: "Connection problems, router basics, and internet confusion.",
    icon: "wifi",
    order: 4,
    featured: true,
    emergencyRelevant: true,
    searchAliases: ["wifi", "internet", "router", "connected"],
  },
  {
    id: "files-storage",
    slug: "files-storage",
    label: "Files & Storage",
    shortDescription: "Downloads, missing files, and storage limits.",
    icon: "folderOpen",
    order: 5,
    featured: true,
    emergencyRelevant: true,
    searchAliases: ["files", "downloads", "storage", "missing file"],
  },
  {
    id: "email",
    slug: "email",
    label: "Email",
    shortDescription: "Attachments, sending trouble, and inbox basics.",
    icon: "mail",
    order: 6,
    featured: true,
    emergencyRelevant: false,
    searchAliases: ["email", "gmail", "attachment", "message"],
  },
  {
    id: "browsers-tabs",
    slug: "browsers-tabs",
    label: "Browsers & Tabs",
    shortDescription: "Tabs, browser clutter, and simple web-browser fixes.",
    icon: "globe",
    order: 7,
    featured: true,
    emergencyRelevant: false,
    searchAliases: ["browser", "tab", "chrome", "firefox", "edge"],
  },
  {
    id: "printing",
    slug: "printing",
    label: "Printing",
    shortDescription: "Offline printers, print queues, and urgent print help.",
    icon: "printer",
    order: 8,
    featured: true,
    emergencyRelevant: true,
    searchAliases: ["print", "printer", "offline printer"],
  },
  {
    id: "safety-scams",
    slug: "safety-scams",
    label: "Safety / Scams / Suspicious Pop-ups",
    shortDescription: "Scary pop-ups, phishing, and digital safety basics.",
    icon: "shieldAlert",
    order: 9,
    featured: true,
    emergencyRelevant: true,
    searchAliases: ["scam", "pop-up", "virus warning", "suspicious"],
  },
  {
    id: "emergency-fixes",
    slug: "emergency-fixes",
    label: "Emergency Fixes",
    shortDescription: "The fastest route when something feels urgent.",
    icon: "siren",
    order: 10,
    featured: true,
    emergencyRelevant: true,
    searchAliases: ["emergency", "urgent", "help now"],
  },
];
