import type { CommonFix } from "@/types/content";

export const commonFixes: CommonFix[] = [
  {
    slug: "forgot-password",
    title: "I forgot my password",
    summary: "Reset a password safely and get back into your account.",
    linkedGuideSlug: "reset-a-forgotten-password",
    category: "accounts-passwords",
    priority: 1,
    symptomPhrases: ["forgot password", "cannot sign in", "password not working"],
    estimatedTimeMinutes: 10,
  },
  {
    slug: "wifi-not-loading",
    title: "Wi-Fi says connected but nothing loads",
    summary: "Work through the quickest connection fixes first.",
    linkedGuideSlug: "reconnect-to-wi-fi",
    category: "wifi-internet",
    priority: 2,
    symptomPhrases: ["connected no internet", "wifi broken", "nothing loads"],
    estimatedTimeMinutes: 8,
  },
  {
    slug: "downloads-missing",
    title: "I downloaded something but cannot find it",
    summary: "Track down files using the places they usually end up.",
    linkedGuideSlug: "find-downloaded-files",
    category: "files-storage",
    priority: 3,
    symptomPhrases: ["missing download", "where did my file go", "cannot find file"],
    estimatedTimeMinutes: 6,
  },
  {
    slug: "storage-full",
    title: "My phone says storage is full",
    summary: "Free space without deleting the wrong things.",
    linkedGuideSlug: "clear-phone-storage",
    category: "phone-problems",
    priority: 4,
    symptomPhrases: ["storage full", "phone full", "cannot take photos"],
    estimatedTimeMinutes: 12,
  },
  {
    slug: "browser-tabs",
    title: "I have too many browser tabs open",
    summary: "Make the browser manageable again without losing important pages.",
    linkedGuideSlug: "manage-too-many-browser-tabs",
    category: "browsers-tabs",
    priority: 5,
    symptomPhrases: ["too many tabs", "browser mess", "too many windows"],
    estimatedTimeMinutes: 5,
  },
  {
    slug: "printer-offline",
    title: "My printer says offline",
    summary: "Check power, connection, and stuck jobs in a safe order.",
    linkedGuideSlug: "fix-a-printer-that-is-offline",
    category: "printing",
    priority: 6,
    symptomPhrases: ["printer offline", "cannot print", "print queue stuck"],
    estimatedTimeMinutes: 10,
  },
];
