import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const accountsAndPasswordsGuides: Guide[] = [
  {
    title: "Change your Windows password",
    slug: "change-your-windows-password",
    category: "accounts-passwords",
    summary: "Use the Windows account settings to change a password you still know before it turns into a lockout.",
    whatThisFixes: ["You want a new password before the old one causes trouble.", "You need a cleaner password you can manage."],
    symptoms: ["You can still sign in.", "You want to change the password on purpose, not recover it."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Normal",
    beforeYouStart: ["Make sure you are using the right Windows account.", "Keep the new password somewhere safe."],
    steps: [
      { title: "Open Windows Settings and go to Accounts", body: ["Look for Sign-in options or Password depending on the Windows version."], image: screenshotPlaceholder("Windows password settings") },
      { title: "Choose the password change option", body: ["Enter your current password first so Windows knows it is really you."] },
      { title: "Create the new password carefully", body: ["Type it twice and make sure it is something you can store safely without guessing."], callouts: [{ tone: "tip", title: "Use a password manager if you can", body: "That reduces the chance of having to recover the account later." }] },
    ],
    tips: ["If the account is synced with Microsoft, the new password may also affect other Microsoft services."],
    warnings: ["Do not change the password if you are unsure whether it is a work or school device with IT rules."],
    fallback: { title: "If this did not work", body: "The device may be using a Microsoft account, work account, or PIN flow that needs a different guide.", actions: ["Try the forgotten-password guide if you no longer know the current password.", "Ask work or school support if the device belongs to them."] },
    relatedGuides: ["reset-a-forgotten-password", "sign-in-code-is-not-arriving"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["change windows password", "update pc password", "new windows login password"],
    media: { heroImage: guideHeroPlaceholder("Windows password guide") },
  },
  {
    title: "Change your Mac login password",
    slug: "change-your-mac-login-password",
    category: "accounts-passwords",
    summary: "Change a Mac password while you still have access so you do not end up locked out later.",
    whatThisFixes: ["You want to replace an old Mac password.", "You can still sign in but need a new one."],
    symptoms: ["You know the current password.", "You want to update the password on a Mac, not recover it."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Normal",
    beforeYouStart: ["Stay signed in to the Mac user account you want to update.", "Keep the new password recorded safely."],
    steps: [
      { title: "Open System Settings and go to Users & Groups", body: ["On some macOS versions this may appear as System Preferences instead of System Settings."], image: screenshotPlaceholder("macOS users and groups settings") },
      { title: "Choose Change Password", body: ["Enter the old password, then the new one twice."] },
      { title: "Add a helpful hint only if it helps you", body: ["A hint should jog your memory without giving the full answer away."] },
    ],
    tips: ["If you use iCloud Keychain or another password manager, update the saved password there too."],
    warnings: ["Do not confuse the Mac password with a website password unless the screen clearly says that is what you are changing."],
    fallback: { title: "If this did not work", body: "You may be using a different kind of account or you may no longer know the current password.", actions: ["Use the forgotten-password guide if you are locked out.", "Ask the device owner or workplace if the Mac is managed."] },
    relatedGuides: ["reset-a-forgotten-password", "fix-a-password-reset-email-that-never-arrives"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["change mac password", "update mac login password", "change macbook password"],
    media: { heroImage: guideHeroPlaceholder("Mac password guide") },
  },
  {
    title: "Password reset email never arrived",
    slug: "fix-a-password-reset-email-that-never-arrives",
    category: "accounts-passwords",
    summary: "Work through the common reasons a password reset email does not show up before trying the request again.",
    whatThisFixes: ["You asked for a reset but no email appeared.", "The reset email may be delayed, filtered, or sent to a different address."],
    symptoms: ["Your inbox is empty.", "Spam or junk may not have been checked yet.", "You are not sure which email address the account uses."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Soon",
    beforeYouStart: ["Wait a minute or two before requesting another email.", "Make sure you are on the official website or app."],
    steps: [
      { title: "Check spam, junk, promotions, and trash", body: ["Reset emails often land outside the main inbox."], image: screenshotPlaceholder("email folders for missing reset email") },
      { title: "Search the inbox for the service name", body: ["Use the company name or a phrase like reset or security in the search box."] },
      { title: "Confirm the account email address", body: ["If you have multiple email addresses, the reset might be going to a different one."] },
      { title: "Request one more reset email slowly", body: ["Too many fast requests can confuse the process or trigger rate limits."] },
    ],
    tips: ["Take a screenshot of the email address you typed so you can verify it later if needed."],
    warnings: ["Do not use reset links from suspicious messages that you did not request yourself."],
    fallback: { title: "If this did not work", body: "The service may be delayed or the account recovery address may be outdated.", actions: ["Try a code-by-text option if the site offers one.", "Use account recovery or contact the service directly from its official help page."] },
    relatedGuides: ["reset-a-forgotten-password", "sign-in-code-is-not-arriving"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["reset email not arriving", "forgot password email not coming", "password reset email missing"],
    media: { heroImage: guideHeroPlaceholder("missing password reset email guide") },
  },
  {
    title: "Sign-in code is not arriving",
    slug: "sign-in-code-is-not-arriving",
    category: "accounts-passwords",
    summary: "Check the most common reasons a text or email sign-in code fails to show up before you try again.",
    whatThisFixes: ["Two-step sign-in code does not arrive.", "You cannot finish sign-in because the code never appears."],
    symptoms: ["No text message appears.", "No email code arrives.", "The app keeps waiting for a code."],
    difficulty: "Easy",
    estimatedTimeMinutes: 8,
    urgency: "Soon",
    beforeYouStart: ["Confirm the phone number or email address on screen is yours.", "Check whether your phone has signal or internet access."],
    steps: [
      { title: "Wait briefly before requesting another code", body: ["Codes can be delayed, and sending too many can slow things down further."] },
      { title: "Check the phone signal, inbox, and spam folders", body: ["The code may be delayed by a weak connection or filtered message."] },
      { title: "Choose a different verification method if offered", body: ["An authenticator app or backup email may be faster than waiting again."], image: screenshotPlaceholder("sign-in code options screen") },
      { title: "Request one fresh code and use only the newest one", body: ["Older codes often expire as soon as a new one is sent."] },
    ],
    tips: ["If you are traveling, time zone or roaming issues can delay some text messages."],
    warnings: ["Never give a code to someone who called, texted, or emailed you first."],
    fallback: { title: "If this did not work", body: "You may need a backup method or formal recovery flow.", actions: ["Try the password reset guide if sign-in is fully blocked.", "Use the service's official recovery process from its real website."] },
    relatedGuides: ["reset-a-forgotten-password", "fix-a-password-reset-email-that-never-arrives"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["verification code not received", "sign in code missing", "2fa code not arriving"],
    media: { heroImage: guideHeroPlaceholder("sign-in code guide") },
  },
];
