import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const browserAndTabGuides: Guide[] = [
  {
    title: "Clear your browser cache",
    slug: "clear-your-browser-cache",
    category: "browsers-tabs",
    summary: "Clear temporary browser data when a website looks broken, outdated, or stuck on the wrong version.",
    whatThisFixes: ["A website loads strangely.", "Pages show old content or login loops."],
    symptoms: ["One site is broken while others work.", "Refreshing does not help.", "The same page may look wrong on one device only."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Soon",
    beforeYouStart: ["Know that clearing cache may sign you out of some sites if you also remove cookies."],
    steps: [
      { title: "Open the browser settings or history menu", body: ["Look for privacy, history, or browsing data options."], image: screenshotPlaceholder("browser clear cache settings") },
      { title: "Choose cached images and files", body: ["If you only need a quick refresh, you may not need to clear every kind of data."] },
      { title: "Clear the data, then close and reopen the browser", body: ["That forces the browser to fetch fresh page files."] },
      { title: "Reload the website and test again", body: ["Check the same page that looked broken before."] },
    ],
    tips: ["If only one site is broken, try a private window before clearing everything."],
    warnings: ["Do not delete saved passwords unless you mean to."],
    fallback: { title: "If this did not work", body: "The problem may be the site itself, an extension, or the internet connection.", actions: ["Try another browser.", "Disable one extension at a time if the issue is only in one browser."] },
    relatedGuides: ["manage-too-many-browser-tabs", "stop-browser-pop-ups"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["clear cache", "browser cache problem", "website looks old or broken"],
    media: { heroImage: guideHeroPlaceholder("browser cache guide") },
  },
  {
    title: "Stop browser pop-ups",
    slug: "stop-browser-pop-ups",
    category: "browsers-tabs",
    summary: "Check browser permissions and settings first when annoying pop-ups keep interrupting normal browsing.",
    whatThisFixes: ["New windows or prompts keep appearing.", "A site keeps pushing alerts or extra tabs."],
    symptoms: ["Pop-ups interrupt browsing.", "Notifications appear from a site you barely remember.", "Extra tabs keep opening."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Soon",
    beforeYouStart: ["Notice whether the pop-ups come from one website or many."],
    steps: [
      { title: "Close the extra tabs or windows first", body: ["Start by stopping the immediate interruption."] },
      { title: "Open browser site settings and review notifications", body: ["Many pop-ups come from sites that were accidentally allowed to send alerts."], image: screenshotPlaceholder("browser notification settings") },
      { title: "Block or remove the noisy site", body: ["Take away permission instead of just dismissing the alerts."] },
      { title: "Restart the browser and test a normal website", body: ["That confirms whether the problem was permission-based or something else."] },
    ],
    tips: ["If the pop-ups look scary or ask for payment, treat them as suspicious rather than urgent."],
    warnings: ["Do not call phone numbers or install tools from browser pop-ups."],
    fallback: { title: "If this did not work", body: "The browser may have a bad extension or notification permission problem.", actions: ["Check installed extensions.", "Use the suspicious pop-up guide if the messages look unsafe."] },
    relatedGuides: ["identify-a-suspicious-pop-up", "turn-off-scam-browser-notifications"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["stop browser popups", "website keeps opening popups", "browser notifications annoying"],
    media: { heroImage: guideHeroPlaceholder("browser pop-up guide") },
  },
  {
    title: "Reopen a tab you closed by mistake",
    slug: "reopen-a-tab-you-closed-by-mistake",
    category: "browsers-tabs",
    summary: "Bring back a closed tab quickly without digging through browser menus too long.",
    whatThisFixes: ["You closed the wrong tab.", "A useful page disappeared by accident."],
    symptoms: ["The tab is gone but was open a moment ago.", "You do not remember the exact website address."],
    difficulty: "Easy",
    estimatedTimeMinutes: 3,
    urgency: "Normal",
    beforeYouStart: ["Stay in the same browser you closed the tab from."],
    steps: [
      { title: "Use the browser option to reopen the last closed tab", body: ["Most browsers keep a recent list of closed tabs and windows."] },
      { title: "Check the history list if the quick reopen option is not enough", body: ["Look for recently closed items first."], image: screenshotPlaceholder("browser history for closed tabs") },
      { title: "Pin or bookmark the page if it matters", body: ["That reduces the chance of losing it again."] },
    ],
    tips: ["If you closed a whole window, many browsers can restore that too."],
    warnings: ["Do not restore a suspicious site just because it was open before."],
    fallback: { title: "If this did not work", body: "The tab may not be recoverable from the browser session anymore.", actions: ["Search the browser history.", "Search the web again using the page topic or site name."] },
    relatedGuides: ["manage-too-many-browser-tabs", "clear-your-browser-cache"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["reopen closed tab", "accidentally closed browser tab", "restore tab"],
    media: { heroImage: guideHeroPlaceholder("reopen tab guide") },
  },
  {
    title: "Make browser text bigger",
    slug: "make-browser-text-bigger",
    category: "browsers-tabs",
    summary: "Increase text size quickly when websites feel hard to read or too cramped.",
    whatThisFixes: ["Web pages feel too small to read.", "You need a fast readability fix without changing the whole computer yet."],
    symptoms: ["Text is tiny.", "You keep zooming in mentally instead of comfortably reading."],
    difficulty: "Easy",
    estimatedTimeMinutes: 3,
    urgency: "Normal",
    beforeYouStart: ["Use the browser you read in most often so the change helps right away."],
    steps: [
      { title: "Use the browser zoom controls first", body: ["Zoom is the fastest way to improve readability on the page you are viewing."] },
      { title: "Set a larger default zoom if small text is a constant problem", body: ["Most browsers let you keep a preferred zoom level."], image: screenshotPlaceholder("browser zoom settings") },
      { title: "Test one or two familiar sites", body: ["That helps you settle on a size that feels readable but not oversized."] },
    ],
    tips: ["Reader mode can help on article pages when the layout feels busy."],
    warnings: ["Avoid browser extensions for this unless the built-in zoom is not enough."],
    fallback: { title: "If this did not work", body: "The operating system text size may also need to be adjusted.", actions: ["Increase system text scaling on Windows, macOS, or iPhone.", "Ask for help if accessibility settings are hard to find."] },
    relatedGuides: ["manage-too-many-browser-tabs", "reopen-a-tab-you-closed-by-mistake"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["browser text too small", "zoom website bigger", "make web page easier to read"],
    media: { heroImage: guideHeroPlaceholder("browser text size guide") },
  },
];
