import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const emailGuides: Guide[] = [
  {
    title: "Email will not send",
    slug: "email-will-not-send",
    category: "email",
    summary: "Check the simplest send blockers first when a message stays stuck in the outbox or keeps failing.",
    whatThisFixes: ["Your email stays in drafts or outbox.", "You press send but the message does not go through."],
    symptoms: ["A send error appears.", "The attachment may be too large.", "The internet connection may be weak."],
    difficulty: "Easy",
    estimatedTimeMinutes: 8,
    urgency: "Soon",
    beforeYouStart: ["Check whether the message includes a large file.", "Make sure you still have internet access."],
    steps: [
      { title: "Confirm the device is online", body: ["A message cannot send if the device has no connection."] },
      { title: "Open the outbox or drafts folder", body: ["Many mail apps show the failed message there with a clearer error."] },
      { title: "Remove or shrink a large attachment if needed", body: ["Very large files often cause sending trouble."], image: screenshotPlaceholder("email attachment size issue") },
      { title: "Close and reopen the mail app, then try again", body: ["That often clears a stuck send process."] },
    ],
    tips: ["If the message is urgent, send a short version first and the file later."],
    warnings: ["Do not keep pressing send repeatedly if the same broken draft is stuck."],
    fallback: { title: "If this did not work", body: "The account connection or outgoing mail settings may need attention.", actions: ["Try the message from a browser version of your email.", "Remove and re-add the account only if you are sure you know the password."] },
    relatedGuides: ["attach-a-file-to-an-email", "find-a-missing-email"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["email not sending", "cannot send email", "message stuck in outbox"],
    media: { heroImage: guideHeroPlaceholder("email sending guide") },
  },
  {
    title: "Find a missing email",
    slug: "find-a-missing-email",
    category: "email",
    summary: "Search the likely folders first when an email seems gone but may just be filtered or moved.",
    whatThisFixes: ["A message is not in the inbox.", "You need an email but do not know where it went."],
    symptoms: ["The email may be archived, filtered, or in spam.", "You know roughly who sent it or when it arrived."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Soon",
    beforeYouStart: ["Know the sender, subject, or date if possible.", "Open the real inbox for the correct account."],
    steps: [
      { title: "Search for the sender or a key word from the subject", body: ["Search is usually faster than manual scrolling."] },
      { title: "Check spam, trash, archive, and promotions folders", body: ["Mail often gets moved automatically."] },
      { title: "Look for filtering rules or category tabs", body: ["The message may have landed in a different view than the main inbox."], image: screenshotPlaceholder("email search and folders") },
      { title: "Sort by newest or unread if the inbox is crowded", body: ["That makes recent important messages easier to spot."] },
    ],
    tips: ["Searching for the sender's domain can be easier than searching the full message subject."],
    warnings: ["Do not trust a look-alike email just because it contains the right company name."],
    fallback: { title: "If this did not work", body: "The email may never have been delivered or it may be in a different account.", actions: ["Ask the sender to resend it.", "Check whether you were looking in the wrong email account."] },
    relatedGuides: ["email-will-not-send", "spot-a-fake-password-reset-email"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["missing email", "cannot find email", "email disappeared"],
    media: { heroImage: guideHeroPlaceholder("missing email guide") },
  },
  {
    title: "Send a photo from iPhone Mail",
    slug: "send-a-photo-from-iphone-mail",
    category: "email",
    summary: "Attach and send a photo from iPhone Mail without getting lost between Photos, Files, and the message composer.",
    whatThisFixes: ["You need to email a photo from an iPhone.", "You are unsure how to attach an image from Photos."],
    symptoms: ["The photo is on the iPhone but not in the email yet.", "The attach controls are hard to find."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Normal",
    beforeYouStart: ["Make sure the photo is already saved on the phone.", "Know the email recipient first if possible."],
    steps: [
      { title: "Open Mail and start a new message", body: ["Enter the recipient before attaching the photo so the draft is clearly set up."] },
      { title: "Tap inside the message body and choose the photo option", body: ["Some versions hide this under the menu or arrow strip above the keyboard."], image: screenshotPlaceholder("iPhone Mail photo attachment controls") },
      { title: "Pick the photo and wait for it to appear in the message", body: ["That confirms the attachment is actually included."] },
      { title: "Send a test to yourself if the photo is important", body: ["It is a quick way to confirm the attachment really went through."] },
    ],
    tips: ["If the image is too large, send fewer photos or share a link instead."],
    warnings: ["Do not send private photos to the wrong address because autocomplete guessed the wrong person."],
    fallback: { title: "If this did not work", body: "The image may be too large or the Mail app may be stuck.", actions: ["Try sharing the photo from the Photos app instead.", "Use another mail app or webmail if the problem continues."] },
    relatedGuides: ["attach-a-file-to-an-email", "find-a-photo-saved-on-iphone"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["send photo by email iphone", "attach picture iphone mail", "email photo from iphone"],
    media: { heroImage: guideHeroPlaceholder("iPhone Mail photo guide") },
  },
  {
    title: "Add an email account on iPhone",
    slug: "add-an-email-account-on-iphone",
    category: "email",
    summary: "Connect a new email account to the iPhone Mail app using the standard settings flow.",
    whatThisFixes: ["You want email on the iPhone.", "A mail account is missing from the Mail app."],
    symptoms: ["Mail only shows one account.", "A new provider has not been added yet.", "You need access on the phone."],
    difficulty: "Medium",
    estimatedTimeMinutes: 10,
    urgency: "Normal",
    beforeYouStart: ["Know the email address and password.", "If the account uses sign-in codes, keep that device nearby."],
    steps: [
      { title: "Open Settings and go to Apps or Mail", body: ["The exact path varies slightly by iOS version, but Mail account settings are still there."], image: screenshotPlaceholder("iPhone add mail account settings") },
      { title: "Choose Accounts, then Add Account", body: ["Pick the provider if it appears, like Google, Outlook, or Yahoo."] },
      { title: "Sign in with the email address and password", body: ["Approve any code or permission request that appears."] },
      { title: "Turn on Mail and save the account", body: ["Open the Mail app after that to confirm the inbox loads."] },
    ],
    tips: ["Provider buttons are easier than manual setup when they are available."],
    warnings: ["Do not enter your password into a fake sign-in page that opens from an untrusted link."],
    fallback: { title: "If this did not work", body: "The provider may need a special app password or a different login method.", actions: ["Check whether two-step verification requires an app password.", "Ask the provider's official help page for the exact iPhone steps."] },
    relatedGuides: ["sign-in-code-is-not-arriving", "email-will-not-send"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["add email to iphone", "set up mail on iphone", "iphone email account setup"],
    media: { heroImage: guideHeroPlaceholder("add iPhone email account guide") },
  },
];
