import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const emergencyFixGuides: Guide[] = [
  {
    title: "Locked out of an account right now",
    slug: "locked-out-of-an-account-right-now",
    category: "emergency-fixes",
    summary: "Use the safest immediate recovery steps first when you need back into an account and cannot wait around.",
    whatThisFixes: ["You cannot sign in right now.", "An important account is inaccessible during something time-sensitive."],
    symptoms: ["Password is rejected.", "The code is not arriving.", "You may have too many failed attempts."],
    difficulty: "Medium",
    estimatedTimeMinutes: 10,
    urgency: "Urgent",
    beforeYouStart: ["Use only the official app or website.", "Do not trust links from random texts or emails during recovery."],
    steps: [
      { title: "Open the official sign-in page yourself", body: ["Type the address manually or use the official app."] },
      { title: "Use the real recovery option once", body: ["Look for Forgot password, Need help signing in, or a similar official link."] },
      { title: "Check all listed recovery channels carefully", body: ["Make sure you are using the right email, phone number, or backup method."], image: screenshotPlaceholder("account recovery options screen") },
      { title: "Use the newest recovery code or email only", body: ["Older codes often stop working as soon as a new one is sent."] },
    ],
    tips: ["Take a breath and avoid rushing between too many different recovery attempts."],
    warnings: ["Do not give a verification code to anyone who contacted you first."],
    fallback: { title: "If this did not work", body: "The account may need a formal recovery request or human support.", actions: ["Try the missing reset email guide.", "Use the service's official help page if recovery is still blocked."] },
    relatedGuides: ["reset-a-forgotten-password", "sign-in-code-is-not-arriving"],
    featured: true,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["locked out account now", "cannot sign in urgent", "account access emergency"],
    media: { heroImage: guideHeroPlaceholder("locked out account emergency guide") },
  },
  {
    title: "Clicked something suspicious right now",
    slug: "clicked-something-suspicious-right-now",
    category: "emergency-fixes",
    summary: "Take the immediate containment steps first when you clicked a link, pop-up, or attachment that now feels wrong.",
    whatThisFixes: ["You clicked a suspicious link.", "A fake warning or message led to a risky action."],
    symptoms: ["The page looked strange.", "A download started unexpectedly.", "You are worried you just trusted the wrong thing."],
    difficulty: "Medium",
    estimatedTimeMinutes: 8,
    urgency: "Urgent",
    beforeYouStart: ["Stop interacting with the suspicious page.", "Do not enter more information."],
    steps: [
      { title: "Close the tab or app right away", body: ["Leave the suspicious content instead of trying to negotiate with it."] },
      { title: "Disconnect from the network if the device starts acting strangely", body: ["That can reduce the chance of more activity while you assess the damage."] },
      { title: "Check whether you downloaded a file or entered a password", body: ["That changes what you need to do next."], image: screenshotPlaceholder("suspicious page follow-up decision points") },
      { title: "Move to the matching recovery guide immediately", body: ["If you entered a password, change it from the real site. If you downloaded something, get help before running it."] },
    ],
    tips: ["Calm, simple containment is better than panic-clicking random “clean up” buttons."],
    warnings: ["Do not call numbers or install tools from the suspicious page."],
    fallback: { title: "If this did not work", body: "The next action depends on what information or files were involved.", actions: ["Use the fake-site password guide if you typed a login.", "Get trusted help if a download opened or installed."] },
    relatedGuides: ["what-to-do-after-entering-a-password-on-a-fake-site", "identify-a-suspicious-pop-up"],
    featured: true,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["clicked suspicious link now", "clicked scam pop up", "urgent suspicious click"],
    media: { heroImage: guideHeroPlaceholder("clicked suspicious item emergency guide") },
  },
  {
    title: "Phone is lost or stolen",
    slug: "phone-is-lost-or-stolen",
    category: "emergency-fixes",
    summary: "Work through the first protective actions quickly when your phone is missing and may be in someone else’s hands.",
    whatThisFixes: ["Your phone is missing.", "You need to protect your data and accounts quickly."],
    symptoms: ["The phone is gone.", "You do not know whether it is nearby or truly lost.", "You are worried about messages, banking, or email access."],
    difficulty: "Medium",
    estimatedTimeMinutes: 12,
    urgency: "Urgent",
    beforeYouStart: ["Use another trusted device.", "Stay calm and work in order instead of changing every account at once."],
    steps: [
      { title: "Try the official find-my-device tool first", body: ["That can help locate, ring, or mark the phone as lost."] },
      { title: "Lock the phone remotely if that option appears", body: ["A remote lock is safer than waiting to see what happens."] },
      { title: "Change the most important account passwords if needed", body: ["Start with email, Apple ID or Google account, and banking-related accounts."], image: screenshotPlaceholder("lost phone recovery priorities") },
      { title: "Contact the carrier if the phone seems truly gone", body: ["They can help suspend the line or protect the account."] },
    ],
    tips: ["Start with the account that can reset other accounts, usually email or the phone platform account."],
    warnings: ["Do not reply to strange recovery texts that appear after the phone goes missing."],
    fallback: { title: "If this did not work", body: "You may need carrier support, police reporting, or account recovery on key services.", actions: ["Gather the device serial or IMEI if you have it.", "Work through password changes one important account at a time."] },
    relatedGuides: ["change-your-mac-login-password", "change-your-windows-password"],
    featured: true,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["phone lost", "phone stolen", "missing iphone urgent"],
    media: { heroImage: guideHeroPlaceholder("lost phone emergency guide") },
  },
  {
    title: "Internet is down before a deadline",
    slug: "internet-is-down-before-a-deadline",
    category: "emergency-fixes",
    summary: "Take the fastest practical steps when the connection dies and you need to get one urgent thing done.",
    whatThisFixes: ["The internet failed at a bad time.", "You need the quickest possible path back online or to a backup plan."],
    symptoms: ["No internet on one or more devices.", "A deadline or meeting is coming up soon.", "Stress is making the problem feel bigger."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Urgent",
    beforeYouStart: ["Decide what the one urgent task is so you can choose the best backup fast."],
    steps: [
      { title: "Check whether your phone can provide a hotspot", body: ["A backup connection may be faster than fully fixing the home network right now."] },
      { title: "Restart the router once if the whole home is offline", body: ["Use a normal restart, not a factory reset."] },
      { title: "Move the urgent task to the working device or connection", body: ["Send the file, join the call, or submit the form using the first path that works."], image: screenshotPlaceholder("urgent internet fallback options") },
      { title: "Return to proper troubleshooting after the urgent task is handled", body: ["Separate the deadline from the deeper network diagnosis."] },
    ],
    tips: ["Under pressure, a backup hotspot is often the smartest first move."],
    warnings: ["Do not spend the deadline window changing advanced router settings."],
    fallback: { title: "If this did not work", body: "You may need a different location, hotspot, or person to submit the urgent item for you.", actions: ["Use another network if possible.", "Ask someone to submit the file or message on your behalf if needed."] },
    relatedGuides: ["restart-a-router-safely", "reconnect-to-wi-fi"],
    featured: true,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["internet down urgent", "wifi dead before meeting", "deadline and no internet"],
    media: { heroImage: guideHeroPlaceholder("internet emergency guide") },
  },
  {
    title: "Need to print something right now",
    slug: "need-to-print-something-right-now",
    category: "emergency-fixes",
    summary: "Prioritize the shortest path to a physical page when printing is urgent and time matters more than perfection.",
    whatThisFixes: ["You need a printout immediately.", "The normal print path is failing and time is tight."],
    symptoms: ["The document is ready but printing is blocked.", "You need one clean copy quickly."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Urgent",
    beforeYouStart: ["Keep the document open on the easiest working device.", "Be willing to switch devices if that is faster."],
    steps: [
      { title: "Choose the simplest available printer path", body: ["Use the device and printer combination that already works if you know one."] },
      { title: "Send one short test page or one-page version first", body: ["That confirms the path before you waste time on a long print job."] },
      { title: "If one device fails, switch devices instead of fighting it too long", body: ["Printing from iPhone, Mac, or Windows may not all fail in the same way."], image: screenshotPlaceholder("urgent print decision path") },
      { title: "Only troubleshoot the queue or printer selection if the fast path fails", body: ["Keep the urgent task separate from deeper printer cleanup."] },
    ],
    tips: ["Exporting to PDF first can make a stubborn document easier to print from another device."],
    warnings: ["Do not resend the same broken job over and over."],
    fallback: { title: "If this did not work", body: "A nearby working printer or another device may be the better emergency answer.", actions: ["Try printing from an iPhone or another laptop.", "Use the print queue or offline printer guides if you still have time."] },
    relatedGuides: ["print-from-an-iphone", "clear-a-stuck-print-queue"],
    featured: true,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["print urgently", "need to print now", "emergency printing"],
    media: { heroImage: guideHeroPlaceholder("urgent print guide") },
  },
];
