import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const filesAndStorageGuides: Guide[] = [
  {
    title: "Free up space on Windows",
    slug: "free-up-space-on-windows",
    category: "files-storage",
    summary: "Use the safe storage checks first when a Windows laptop is low on space and everything feels tighter than usual.",
    whatThisFixes: ["The drive is nearly full.", "Updates, downloads, or new files are failing because there is not enough room."],
    symptoms: ["Windows warns about low storage.", "Saving files is harder than usual.", "The laptop may feel slower."],
    difficulty: "Easy",
    estimatedTimeMinutes: 12,
    urgency: "Soon",
    beforeYouStart: ["Do not delete files you do not recognize yet.", "Make sure important documents are backed up if possible."],
    steps: [
      { title: "Open Storage settings to see what is using space", body: ["That is safer than guessing folder by folder."], image: screenshotPlaceholder("Windows storage settings") },
      { title: "Delete obvious large files from Downloads first", body: ["Old installers, videos, and duplicate files are common space hogs."] },
      { title: "Empty the Recycle Bin if the deleted files are no longer needed", body: ["Files in the Recycle Bin still take up space until you clear it."] },
      { title: "Move large personal files off the laptop if needed", body: ["An external drive or cloud folder can free space without permanent deletion."] },
    ],
    tips: ["The Downloads folder is often the fastest safe place to check first."],
    warnings: ["Do not delete system folders or app folders unless you know exactly what they are."],
    fallback: { title: "If this did not work", body: "The drive may be crowded by apps, backups, or hidden files.", actions: ["Remove unused apps carefully.", "Ask for help before deleting anything that looks system-related."] },
    relatedGuides: ["find-downloaded-files", "windows-laptop-feels-very-slow"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["free up space windows", "pc storage full", "windows low disk space"],
    media: { heroImage: guideHeroPlaceholder("Windows storage guide") },
  },
  {
    title: "Free up space on a Mac",
    slug: "free-up-space-on-mac",
    category: "files-storage",
    summary: "Use the Mac storage view first when space is tight and you need room without deleting the wrong thing.",
    whatThisFixes: ["The Mac says the disk is almost full.", "Saving, downloading, or updating is harder because storage is tight."],
    symptoms: ["Storage warnings appear.", "The Mac feels crowded or slower than usual.", "Big updates will not start."],
    difficulty: "Easy",
    estimatedTimeMinutes: 12,
    urgency: "Soon",
    beforeYouStart: ["Do not delete unfamiliar library or system files.", "Back up important files if possible."],
    steps: [
      { title: "Open Storage in System Settings", body: ["This shows the biggest categories before you start deleting."] , image: screenshotPlaceholder("macOS storage overview") },
      { title: "Check Downloads and large video files first", body: ["These are often the easiest files to remove or move elsewhere."] },
      { title: "Empty Trash only after checking it", body: ["Trash still counts against storage until you empty it."] },
      { title: "Move large personal files to another safe location if needed", body: ["An external drive or cloud storage can buy back space without losing everything."] },
    ],
    tips: ["If Photos or Messages are using a lot of space, review them slowly rather than deleting blindly."],
    warnings: ["Avoid “cleaner” apps that promise magic fixes."],
    fallback: { title: "If this did not work", body: "The Mac may be using space for apps, caches, or local backups that need a closer look.", actions: ["Remove apps you no longer need.", "Get help before deleting anything inside system folders."] },
    relatedGuides: ["find-downloaded-files", "mac-feels-slow-and-cluttered"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["free up space mac", "mac storage full", "macbook disk almost full"],
    media: { heroImage: guideHeroPlaceholder("Mac storage guide") },
  },
  {
    title: "Recover a file from Trash or Recycle Bin",
    slug: "recover-a-file-from-trash-or-recycle-bin",
    category: "files-storage",
    summary: "Check the deleted-items area first when a file seems gone but may still be recoverable.",
    whatThisFixes: ["A file was deleted by mistake.", "You need to restore something you removed too quickly."],
    symptoms: ["The file is gone from its folder.", "You think it may have been deleted, not permanently erased."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Soon",
    beforeYouStart: ["Stop deleting more files until you check the trash area.", "Remember the file name if you can."],
    steps: [
      { title: "Open Trash on Mac or Recycle Bin on Windows", body: ["Look there before trying anything more complicated."], image: screenshotPlaceholder("Trash or Recycle Bin view") },
      { title: "Search or sort by recent deletion", body: ["That helps when there are many files inside."] },
      { title: "Restore the file to its original location", body: ["Use Restore on Windows or Put Back on Mac if the option appears."] },
      { title: "Open the restored file to confirm it still works", body: ["A quick check now prevents surprise later."] },
    ],
    tips: ["If you know the file type, search by extension or sort by kind."],
    warnings: ["If Trash or Recycle Bin has already been emptied, do not install random recovery tools from ads."],
    fallback: { title: "If this did not work", body: "The file may be in another folder, a cloud service, or already permanently removed.", actions: ["Search the computer by file name.", "Check the cloud service trash if the file was synced."] },
    relatedGuides: ["find-downloaded-files", "free-up-space-on-windows"],
    featured: false,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["restore deleted file", "recover from recycle bin", "file in trash"],
    media: { heroImage: guideHeroPlaceholder("recover deleted file guide") },
  },
  {
    title: "Find a photo saved on iPhone",
    slug: "find-a-photo-saved-on-iphone",
    category: "files-storage",
    summary: "Use the iPhone Photos and Files views to track down a saved image without guessing where it went.",
    whatThisFixes: ["A photo or screenshot was saved but seems missing.", "You are not sure whether it went to Photos or Files."],
    symptoms: ["You saved or downloaded an image on iPhone.", "You cannot find it in the expected place."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Normal",
    beforeYouStart: ["Think about whether the image was downloaded, screenshotted, or shared from another app."],
    steps: [
      { title: "Check the Photos app first", body: ["Screenshots and many shared images appear there even when they started in another app."] },
      { title: "Use Search in Photos for a place, object, or date", body: ["Search is often faster than scrolling through the whole library."] },
      { title: "Open the Files app and check Downloads if it came from Safari or Mail", body: ["Some saved items go to Files instead of Photos."], image: screenshotPlaceholder("iPhone Files downloads screen") },
      { title: "Check the recent items list in the app you used", body: ["Mail, Safari, and Messages can all give useful hints about where the item went."] },
    ],
    tips: ["If you just took a screenshot, look in the Screenshots album specifically."],
    warnings: ["Do not assume a missing photo is deleted until you check both Photos and Files."],
    fallback: { title: "If this did not work", body: "The image may not have finished saving or may be in cloud storage instead.", actions: ["Try downloading or saving it again.", "Check the app it came from one more time."] },
    relatedGuides: ["find-downloaded-files", "attach-a-file-to-an-email"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["find photo on iphone", "where did iphone save picture", "saved image missing iphone"],
    media: { heroImage: guideHeroPlaceholder("iPhone saved photo guide") },
  },
];
