import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const laptopBasicsGuides: Guide[] = [
  {
    title: "Windows laptop feels very slow",
    slug: "windows-laptop-feels-very-slow",
    category: "laptop-basics",
    summary: "Start with the checks that most often improve a slow Windows laptop without changing anything risky.",
    whatThisFixes: ["Programs open slowly.", "The laptop feels sluggish during simple tasks."],
    symptoms: ["Fans run loudly.", "Web pages take longer than usual.", "The desktop responds slowly."],
    difficulty: "Easy",
    estimatedTimeMinutes: 12,
    urgency: "Soon",
    beforeYouStart: ["Plug the laptop into power if the battery is low.", "Save any open work before restarting."],
    steps: [
      { title: "Restart the laptop once", body: ["A clean restart clears many temporary slowdowns."] },
      { title: "Check Task Manager for one app using too much memory or CPU", body: ["If one process is taking nearly everything, that is usually the first thing to close."], image: screenshotPlaceholder("Windows Task Manager") },
      { title: "Close extra tabs and programs you are not using", body: ["Too many browser tabs or startup apps can make simple tasks feel heavy."] },
      { title: "Install pending Windows updates later if needed", body: ["Updates can help, but do not start a big update if you need the laptop immediately."] },
    ],
    tips: ["If the slowdown started today, think about the last app or update that changed."],
    warnings: ["Do not install random cleanup tools from ads or pop-ups."],
    fallback: { title: "If this did not work", body: "The laptop may be low on storage, overloaded at startup, or dealing with hardware problems.", actions: ["Free up storage if the drive is nearly full.", "Ask for help if the laptop stays slow after restarting."] },
    relatedGuides: ["free-up-space-on-windows", "manage-too-many-browser-tabs"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["windows laptop slow", "pc very slow", "computer running slow windows"],
    media: { heroImage: guideHeroPlaceholder("slow Windows laptop guide") },
  },
  {
    title: "Mac feels slow and cluttered",
    slug: "mac-feels-slow-and-cluttered",
    category: "laptop-basics",
    summary: "Use the fastest checks first when a Mac feels heavy, crowded, or slower than it should.",
    whatThisFixes: ["The Mac takes longer to open apps.", "The desktop feels crowded and harder to manage."],
    symptoms: ["Too many windows or startup items.", "Storage may be nearly full.", "Apps take a while to respond."],
    difficulty: "Easy",
    estimatedTimeMinutes: 12,
    urgency: "Soon",
    beforeYouStart: ["Save your work before restarting.", "Plug in the Mac if the battery is very low."],
    steps: [
      { title: "Restart the Mac", body: ["This clears temporary background clutter and gives you a fresh baseline."] },
      { title: "Close extra windows, browser tabs, and startup apps", body: ["A crowded desktop often reflects too many active processes."] },
      { title: "Check Storage in System Settings", body: ["A nearly full drive can make the whole Mac feel slower."], image: screenshotPlaceholder("macOS storage settings") },
      { title: "Update macOS or the one troublesome app later", body: ["If the slowdown started after a known problem, updates may help once you have time."] },
    ],
    tips: ["Moving old downloads and large videos off the Mac often helps more than small cleanup tweaks."],
    warnings: ["Do not install aggressive cleaner apps just because they promise instant speed."],
    fallback: { title: "If this did not work", body: "The slowdown may come from low storage, memory pressure, or hardware aging.", actions: ["Try the Mac storage guide next.", "Get help if the Mac overheats or freezes often."] },
    relatedGuides: ["free-up-space-on-mac", "manage-too-many-browser-tabs"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["mac slow", "macbook feels slow", "mac cluttered and slow"],
    media: { heroImage: guideHeroPlaceholder("slow Mac guide") },
  },
  {
    title: "Connect Bluetooth headphones on Windows",
    slug: "connect-bluetooth-headphones-on-windows",
    category: "laptop-basics",
    summary: "Pair Bluetooth headphones to a Windows laptop without getting stuck in the settings maze.",
    whatThisFixes: ["Headphones will not connect.", "You are not sure where Bluetooth pairing happens in Windows."],
    symptoms: ["The headphones are in pairing mode but not showing up.", "Windows sees the device but does not finish connecting."],
    difficulty: "Easy",
    estimatedTimeMinutes: 8,
    urgency: "Normal",
    beforeYouStart: ["Charge the headphones if possible.", "Put the headphones in pairing mode before opening Bluetooth settings."],
    steps: [
      { title: "Open Bluetooth & devices in Windows Settings", body: ["Use the search box if you do not see Bluetooth right away."], image: screenshotPlaceholder("Windows Bluetooth settings") },
      { title: "Choose Add device and wait for the headphones to appear", body: ["Stay close to the laptop while the device is pairing."] },
      { title: "Select the headphones and confirm the connection", body: ["If Windows asks for permission, accept the pairing request."] },
      { title: "Set the headphones as the active sound output if needed", body: ["Sometimes pairing works, but the laptop is still sending audio to its speakers."] },
    ],
    tips: ["If the headphones were recently connected to a phone, disconnect them there first."],
    warnings: ["Do not keep adding the same device repeatedly if it already shows up in the paired list."],
    fallback: { title: "If this did not work", body: "Bluetooth may be off, the headphones may still be paired elsewhere, or Windows may need a restart.", actions: ["Restart Bluetooth and try again.", "Forget the device and re-pair it once."] },
    relatedGuides: ["windows-laptop-feels-very-slow", "connect-bluetooth-headphones-on-a-mac"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["pair bluetooth headphones windows", "connect earbuds to pc", "windows bluetooth headphones"],
    media: { heroImage: guideHeroPlaceholder("Windows Bluetooth guide") },
  },
  {
    title: "Connect Bluetooth headphones on a Mac",
    slug: "connect-bluetooth-headphones-on-a-mac",
    category: "laptop-basics",
    summary: "Pair Bluetooth headphones to a Mac with the fewest steps and the least confusion.",
    whatThisFixes: ["Headphones are not pairing with the Mac.", "You are not sure where Bluetooth devices appear on macOS."],
    symptoms: ["The headphones do not show up.", "The Mac pairs but still plays sound through the speakers."],
    difficulty: "Easy",
    estimatedTimeMinutes: 8,
    urgency: "Normal",
    beforeYouStart: ["Charge the headphones.", "Put them in pairing mode before you open Bluetooth settings."],
    steps: [
      { title: "Open System Settings and choose Bluetooth", body: ["Make sure Bluetooth is turned on first."], image: screenshotPlaceholder("macOS Bluetooth settings") },
      { title: "Wait for the headphones to appear, then choose Connect", body: ["Stay near the Mac and keep the headphones in pairing mode."] },
      { title: "Confirm the headphones are the active audio output", body: ["Use Sound settings or the Control Center audio chooser if needed."] },
      { title: "Test with a short video or sound clip", body: ["That confirms both pairing and playback."] },
    ],
    tips: ["If the headphones keep reconnecting to an iPhone, disconnect them there first."],
    warnings: ["Do not remove every Bluetooth device from the Mac unless you know you need to re-pair them all."],
    fallback: { title: "If this did not work", body: "The headphones may still be attached to another device or Bluetooth may need a restart.", actions: ["Turn Bluetooth off and on once.", "Forget the headphones and pair again."] },
    relatedGuides: ["mac-feels-slow-and-cluttered", "connect-bluetooth-headphones-on-windows"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["pair bluetooth headphones mac", "connect airpods to mac", "mac bluetooth headphones"],
    media: { heroImage: guideHeroPlaceholder("Mac Bluetooth guide") },
  },
  {
    title: "Laptop camera is not working",
    slug: "laptop-camera-is-not-working",
    category: "laptop-basics",
    summary: "Check the fastest privacy and permissions settings first when the laptop camera stays black.",
    whatThisFixes: ["Video calls cannot see the camera.", "The camera app or meeting app shows a black screen."],
    symptoms: ["The camera light may stay off.", "Apps say the camera is unavailable.", "A privacy cover may still be closed."],
    difficulty: "Easy",
    estimatedTimeMinutes: 9,
    urgency: "Soon",
    beforeYouStart: ["Check whether the laptop has a physical camera shutter.", "Close any other app that might already be using the camera."],
    steps: [
      { title: "Check the physical shutter or camera key first", body: ["Some laptops have a hardware switch or key that blocks the camera completely."] },
      { title: "Test the camera in the built-in camera app", body: ["This shows whether the problem is system-wide or only one app."] },
      { title: "Review camera permissions for the app you are using", body: ["Windows and macOS both let apps lose camera access by accident."], image: screenshotPlaceholder("laptop camera permission settings") },
      { title: "Restart the laptop and the meeting app", body: ["That clears a camera lock that another app may have left behind."] },
    ],
    tips: ["If the camera works in one app but not another, the problem is usually permissions or the app’s chosen camera source."],
    warnings: ["Do not install mystery driver tools from ads to fix a camera problem."],
    fallback: { title: "If this did not work", body: "The issue may be a driver problem, app problem, or a physical camera fault.", actions: ["Try another meeting app or browser.", "Ask for help if the camera is missing everywhere."] },
    relatedGuides: ["windows-laptop-feels-very-slow", "mac-feels-slow-and-cluttered"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["laptop camera not working", "webcam black screen", "camera unavailable on laptop"],
    media: { heroImage: guideHeroPlaceholder("laptop camera guide") },
  },
];
