import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const phoneProblemGuides: Guide[] = [
  {
    title: "iPhone battery is draining too fast",
    slug: "iphone-battery-is-draining-too-fast",
    category: "phone-problems",
    summary: "Use the fastest battery checks first when an iPhone suddenly starts losing charge too quickly.",
    whatThisFixes: ["The battery falls quickly even with light use.", "The phone now needs charging much more often."],
    symptoms: ["Battery percentage drops fast.", "The phone feels warm during normal use.", "Background apps may be more active than usual."],
    difficulty: "Easy",
    estimatedTimeMinutes: 10,
    urgency: "Normal",
    beforeYouStart: ["Have a charger nearby in case the battery is already low.", "Let the phone cool down if it feels hot."],
    steps: [
      { title: "Open Battery settings and check what used the most power", body: ["Look for one app or activity using far more battery than expected."], image: screenshotPlaceholder("iPhone battery settings") },
      { title: "Reduce screen brightness and turn off Low Power blockers", body: ["High brightness and constant background activity make battery drain feel worse."], callouts: [{ tone: "tip", title: "Low Power Mode is fine to use", body: "It can buy you time while you figure out what changed." }] },
      { title: "Restart the iPhone once", body: ["A simple restart often clears a stuck background process."] },
      { title: "Install any pending iOS update", body: ["Battery bugs sometimes improve after the next update."] },
    ],
    tips: ["If the problem started right after a new app install, check that app first."],
    warnings: ["Do not use unknown battery cleaner apps."],
    fallback: { title: "If this did not work", body: "The battery health may be low or an app may still be misbehaving.", actions: ["Check Battery Health in iPhone settings.", "Ask Apple Support or a repair shop if battery health is very low."] },
    relatedGuides: ["clear-phone-storage", "iphone-wont-update"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["iphone battery draining fast", "phone battery dying quickly", "iphone losing charge fast"],
    media: { heroImage: guideHeroPlaceholder("iPhone battery guide") },
  },
  {
    title: "iPhone will not update",
    slug: "iphone-wont-update",
    category: "phone-problems",
    summary: "Check storage, power, and Wi-Fi before assuming the update itself is broken.",
    whatThisFixes: ["iOS update will not start.", "The update download or install keeps failing."],
    symptoms: ["The update button does nothing.", "A message says there is not enough space.", "The phone restarts without finishing."],
    difficulty: "Medium",
    estimatedTimeMinutes: 12,
    urgency: "Soon",
    beforeYouStart: ["Connect to Wi-Fi.", "Plug the phone into power if the battery is low.", "Make sure there is enough free storage."],
    steps: [
      { title: "Check available storage first", body: ["Updates often fail when the phone is nearly full."], image: screenshotPlaceholder("iPhone storage before update") },
      { title: "Verify the iPhone is on stable Wi-Fi and power", body: ["Updates are much less reliable on weak connections or low battery."] },
      { title: "Restart the phone and try again", body: ["This clears temporary update glitches."] },
      { title: "Delete the partial update if one is stuck", body: ["In iPhone Storage, remove the failed update file and download it again."], callouts: [{ tone: "warning", title: "Delete only the update file", body: "Do not erase the phone or reset all settings for a normal update problem." }] },
    ],
    tips: ["Clearing a little extra space before a large update helps more than cutting it close."],
    warnings: ["Do not force multiple interrupted update attempts in a row if the phone is already acting unstable."],
    fallback: { title: "If this did not work", body: "The update may need a computer-assisted install or there may be a deeper device issue.", actions: ["Try again later in case Apple services are busy.", "Use Finder or iTunes from a trusted computer if you know how.", "Get help before doing a full restore."] },
    relatedGuides: ["clear-phone-storage", "reconnect-to-wi-fi"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["iphone update failed", "ios update not working", "iphone wont update"],
    media: { heroImage: guideHeroPlaceholder("iPhone update guide") },
  },
  {
    title: "iPhone screen is frozen",
    slug: "iphone-screen-is-frozen",
    category: "phone-problems",
    summary: "Use the calm recovery steps first when an iPhone stops responding to taps or swipes.",
    whatThisFixes: ["The screen is stuck.", "Apps or the whole iPhone stopped responding."],
    symptoms: ["You cannot tap anything.", "The screen looks on but nothing moves.", "Buttons may still work or vibrate."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Soon",
    beforeYouStart: ["Plug the phone into power if the battery may be low.", "Remove bulky gloves or screen covers that can confuse touch."],
    steps: [
      { title: "Wait a few seconds to see if the phone recovers", body: ["A heavily loaded app can briefly freeze before it catches up."] },
      { title: "Force close the stuck app if you still can", body: ["If the problem is only one app, closing it may be enough."] },
      { title: "Force restart the iPhone", body: ["Use the correct button sequence for your model to restart without erasing anything."], image: screenshotPlaceholder("iPhone force restart reference") },
      { title: "Unlock the phone and test a simple app", body: ["This confirms whether the freeze was temporary or still active."] },
    ],
    tips: ["If freezing started after a particular app update, note the app name so you can update or remove it later."],
    warnings: ["Do not keep pressing random button combinations that could trigger emergency features or accessibility shortcuts."],
    fallback: { title: "If this did not work", body: "The iPhone may need an update, more free storage, or repair.", actions: ["Restart again after charging for a while.", "Check storage and pending updates when it becomes responsive.", "Get help if the screen stays unresponsive."] },
    relatedGuides: ["clear-phone-storage", "iphone-wont-update"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["iphone frozen", "phone screen stuck", "iphone not responding"],
    media: { heroImage: guideHeroPlaceholder("frozen iPhone guide") },
  },
  {
    title: "iPhone is not ringing",
    slug: "iphone-is-not-ringing",
    category: "phone-problems",
    summary: "Check the quiet-mode settings first when calls are coming in but the iPhone stays silent.",
    whatThisFixes: ["Calls arrive silently.", "The phone vibrates or lights up but does not ring."],
    symptoms: ["Missed calls with no sound.", "Silent Mode or Focus may be active.", "Volume may be turned down."],
    difficulty: "Easy",
    estimatedTimeMinutes: 5,
    urgency: "Normal",
    beforeYouStart: ["Ask someone to call you for testing if possible.", "Make sure the phone speaker is not blocked."],
    steps: [
      { title: "Check the Ring or Silent switch and volume buttons", body: ["Make sure the phone is not set to silent and the ringer volume is not too low."], image: screenshotPlaceholder("iPhone ringer settings") },
      { title: "Review Focus or Do Not Disturb settings", body: ["A Focus mode can silence calls without looking obvious on the home screen."] },
      { title: "Open Sounds & Haptics and choose a ringtone", body: ["This confirms the phone still has an active ringtone selected."] },
      { title: "Restart the phone and test one more call", body: ["That rules out a temporary audio glitch."] },
    ],
    tips: ["If calls from one person are silent but others ring, check whether that contact is set to emergency bypass or custom silence."],
    warnings: ["Do not erase the phone for a ringtone problem."],
    fallback: { title: "If this did not work", body: "The issue may be speaker-related, network-related, or tied to one contact.", actions: ["Test other sounds like music or videos.", "Check whether the carrier has a calling issue.", "Get help if the speaker seems damaged."] },
    relatedGuides: ["iphone-screen-is-frozen", "reconnect-to-wi-fi"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["iphone not ringing", "phone calls silent", "iphone calls no sound"],
    media: { heroImage: guideHeroPlaceholder("iPhone ringing guide") },
  },
];
