import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const printingGuides: Guide[] = [
  {
    title: "Set the right printer on Windows",
    slug: "set-the-right-printer-on-windows",
    category: "printing",
    summary: "Pick the correct printer in Windows when the job keeps going to the wrong device or nowhere at all.",
    whatThisFixes: ["Print jobs go to the wrong printer.", "Windows keeps choosing a printer you do not want."],
    symptoms: ["Nothing prints on the expected printer.", "The wrong office or home printer is selected."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Soon",
    beforeYouStart: ["Know the printer name if possible.", "Make sure the printer is turned on."],
    steps: [
      { title: "Open the print window and check the selected printer", body: ["The wrong printer is often still selected from the last job."], image: screenshotPlaceholder("Windows print dialog printer chooser") },
      { title: "Choose the correct printer from the list", body: ["Look for the exact printer name rather than guessing."] },
      { title: "Open Windows printer settings if the device is missing", body: ["Confirm the printer is still installed and available."] },
      { title: "Print one simple test page", body: ["A short test is faster than sending the full document again."] },
    ],
    tips: ["If you only use one printer at home, setting it as default can reduce future confusion."],
    warnings: ["Do not remove every printer from Windows unless you are ready to add them back."],
    fallback: { title: "If this did not work", body: "The printer may be offline, disconnected, or stuck in the queue.", actions: ["Try the offline printer guide.", "Check the print queue for stalled jobs."] },
    relatedGuides: ["fix-a-printer-that-is-offline", "clear-a-stuck-print-queue"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["select printer windows", "wrong printer selected windows", "set default printer windows"],
    media: { heroImage: guideHeroPlaceholder("Windows printer selection guide") },
  },
  {
    title: "Set the right printer on a Mac",
    slug: "set-the-right-printer-on-a-mac",
    category: "printing",
    summary: "Choose the correct printer on a Mac when the print job keeps aiming at the wrong device.",
    whatThisFixes: ["The Mac keeps choosing the wrong printer.", "The document is ready but not going to the expected device."],
    symptoms: ["Another printer keeps appearing by default.", "The right printer exists but is not selected."],
    difficulty: "Easy",
    estimatedTimeMinutes: 6,
    urgency: "Soon",
    beforeYouStart: ["Know the printer name if possible.", "Make sure the printer is on and connected."],
    steps: [
      { title: "Open the print window and check the printer menu", body: ["The wrong device may simply still be selected from last time."], image: screenshotPlaceholder("macOS print dialog printer chooser") },
      { title: "Pick the correct printer and confirm any preset options", body: ["That is especially important if the printer has similar names."] },
      { title: "Open Printers & Scanners if the right device is missing", body: ["This shows whether the Mac still sees the printer at all."] },
      { title: "Send a short test page", body: ["Testing with one page is faster than resending a long document."] },
    ],
    tips: ["The Mac can remember the last printer used, which is helpful until it is not."],
    warnings: ["Do not delete all printers unless you are comfortable setting them up again."],
    fallback: { title: "If this did not work", body: "The printer may be offline or the queue may be stuck.", actions: ["Use the offline printer guide.", "Clear the print queue and try again."] },
    relatedGuides: ["fix-a-printer-that-is-offline", "clear-a-stuck-print-queue"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["select printer mac", "wrong printer selected mac", "set printer on mac"],
    media: { heroImage: guideHeroPlaceholder("Mac printer selection guide") },
  },
  {
    title: "Clear a stuck print queue",
    slug: "clear-a-stuck-print-queue",
    category: "printing",
    summary: "Remove stalled print jobs when one bad queue item keeps blocking everything else behind it.",
    whatThisFixes: ["A document is stuck and nothing else prints.", "The queue says printing forever."],
    symptoms: ["Jobs pile up behind one broken item.", "The printer appears busy but nothing comes out."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Soon",
    beforeYouStart: ["Do not keep sending the same document again while the queue is stuck."],
    steps: [
      { title: "Open the printer queue view", body: ["Use printer settings on Windows or Mac to find the current job list."], image: screenshotPlaceholder("printer queue view") },
      { title: "Cancel the stuck job first", body: ["One broken job can block every job after it."] },
      { title: "Wait a moment, then restart the printer if needed", body: ["That helps the queue clear fully."] },
      { title: "Send one short test page", body: ["Testing with one page is the safest way to confirm the queue is healthy again."] },
    ],
    tips: ["Large PDFs are common queue blockers, especially on older printers."],
    warnings: ["Do not keep duplicating the same print job into the queue."],
    fallback: { title: "If this did not work", body: "The printer connection may be offline or the document itself may be causing trouble.", actions: ["Try the offline printer guide.", "Print a different one-page document to compare."] },
    relatedGuides: ["fix-a-printer-that-is-offline", "set-the-right-printer-on-windows"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["stuck print queue", "clear printer queue", "printer jobs stuck"],
    media: { heroImage: guideHeroPlaceholder("print queue guide") },
  },
  {
    title: "Print from an iPhone",
    slug: "print-from-an-iphone",
    category: "printing",
    summary: "Use the built-in share and print flow on iPhone when you need a fast print without moving the file first.",
    whatThisFixes: ["You need to print from an iPhone.", "The document or photo is on the phone and needs to get to a printer."],
    symptoms: ["The file opens on iPhone but you do not see the print button right away.", "You are not sure whether the printer is available from the phone."],
    difficulty: "Medium",
    estimatedTimeMinutes: 8,
    urgency: "Soon",
    beforeYouStart: ["Make sure the iPhone and printer are on the same Wi-Fi if the printer needs AirPrint.", "Open the exact photo or document first."],
    steps: [
      { title: "Open the file or photo you want to print", body: ["Start from the actual document so you do not lose time switching apps."] },
      { title: "Use the Share button and look for Print", body: ["Some apps place Print farther down the share sheet."], image: screenshotPlaceholder("iPhone print option in share sheet") },
      { title: "Choose the printer and review copies or page range", body: ["This is where you confirm the right device before sending anything."] },
      { title: "Tap Print and wait a moment for the job to appear", body: ["A slow printer discovery step does not always mean failure."] },
    ],
    tips: ["If Print is missing, try opening the file in Files or another app that supports printing."],
    warnings: ["Do not keep sending repeat prints if the printer is still unavailable."],
    fallback: { title: "If this did not work", body: "The printer may not support iPhone printing or may not be on the same network.", actions: ["Try printing from a laptop instead.", "Use the offline printer guide if the printer should already be reachable."] },
    relatedGuides: ["fix-a-printer-that-is-offline", "need-to-print-something-right-now"],
    featured: false,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["print from iphone", "airprint not working", "iphone document printing"],
    media: { heroImage: guideHeroPlaceholder("iPhone printing guide") },
  },
];
