import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const safetyAndScamGuides: Guide[] = [
  {
    title: "Spot a fake password reset email",
    slug: "spot-a-fake-password-reset-email",
    category: "safety-scams",
    summary: "Use a few fast checks to tell the difference between a real password reset email and a phishing attempt.",
    whatThisFixes: ["You received a password reset email you do not trust.", "The message looks urgent and may be fake."],
    symptoms: ["The email pushes urgency.", "The sender address looks strange.", "The link destination is unclear."],
    difficulty: "Easy",
    estimatedTimeMinutes: 5,
    urgency: "Urgent",
    beforeYouStart: ["Do not click the email links yet.", "Open the real website separately if you want to check the account."] ,
    steps: [
      { title: "Read the sender address carefully", body: ["A fake sender often uses a close-looking but wrong domain."] },
      { title: "Look for pressure, threats, or odd wording", body: ["Scam messages often try to rush you before you think clearly."] },
      { title: "Check whether you actually requested a reset", body: ["An unexpected reset email should be treated cautiously."], image: screenshotPlaceholder("suspicious password reset email example") },
      { title: "Go to the service directly instead of using the email link", body: ["Type the real website yourself or use the official app."] },
    ],
    tips: ["A real company may send a reset email you did not request, but you should still open the account directly rather than trust the message."],
    warnings: ["Do not enter your password after clicking a suspicious reset link."],
    fallback: { title: "If this did not work", body: "If you already clicked or entered information, switch to the fake-site recovery guide now.", actions: ["Change the password from the real site.", "Enable two-step verification if available."] },
    relatedGuides: ["what-to-do-after-entering-a-password-on-a-fake-site", "reset-a-forgotten-password"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["fake password reset email", "phishing password email", "suspicious reset message"],
    media: { heroImage: guideHeroPlaceholder("fake reset email guide") },
  },
  {
    title: "What to do after entering a password on a fake site",
    slug: "what-to-do-after-entering-a-password-on-a-fake-site",
    category: "safety-scams",
    summary: "Move quickly but calmly if you typed a password into a site that now seems fake or unsafe.",
    whatThisFixes: ["You entered a password on a phishing page.", "You think scammers may now have your login details."],
    symptoms: ["The site looked strange after the fact.", "A pop-up or email led you there.", "You entered a password and now feel unsure."],
    difficulty: "Medium",
    estimatedTimeMinutes: 10,
    urgency: "Urgent",
    beforeYouStart: ["Use the official website or app, not the suspicious page, for every next step.", "Stay calm and work one action at a time."],
    steps: [
      { title: "Go to the real service and change the password immediately", body: ["Use a new password, not a slight variation of the old one."] },
      { title: "Sign out of other sessions if the service offers that option", body: ["That can remove access from devices or browsers you do not trust."] },
      { title: "Turn on two-step verification", body: ["That adds a second barrier if the password has already been exposed."], image: screenshotPlaceholder("account security settings after phishing") },
      { title: "Check for recent account changes", body: ["Look for new devices, forwarding rules, or messages you did not send."] },
    ],
    tips: ["If you reused the same password anywhere else, change those accounts too."],
    warnings: ["Do not stay on the fake site while you are trying to fix the account."],
    fallback: { title: "If this did not work", body: "If you cannot get back in, use the account recovery process right away.", actions: ["Use the locked-out emergency guide.", "Contact the service through its official support page if recovery fails."] },
    relatedGuides: ["locked-out-of-an-account-right-now", "spot-a-fake-password-reset-email"],
    featured: true,
    commonFix: false,
    emergencyRelevant: true,
    searchAliases: ["entered password on fake site", "phishing password mistake", "typed password into scam website"],
    media: { heroImage: guideHeroPlaceholder("fake site password recovery guide") },
  },
  {
    title: "Check whether a text message is a scam",
    slug: "check-whether-a-text-message-is-a-scam",
    category: "safety-scams",
    summary: "Use fast common-sense checks before trusting a text that demands action, payment, or a login.",
    whatThisFixes: ["A text message feels suspicious.", "You are not sure whether the sender is real."],
    symptoms: ["The message is urgent.", "It asks for payment or login details.", "The link looks shortened or unfamiliar."],
    difficulty: "Easy",
    estimatedTimeMinutes: 4,
    urgency: "Urgent",
    beforeYouStart: ["Do not tap the link yet.", "Do not reply to the number yet."],
    steps: [
      { title: "Read the message slowly and look for pressure tactics", body: ["Scam texts often try to create panic or rush."] },
      { title: "Inspect the link or phone number carefully", body: ["Shortened links and odd sender names are major clues."] },
      { title: "Verify through the real company or person another way", body: ["Use the official app, website, or a known saved contact instead."], image: screenshotPlaceholder("suspicious text message example") },
      { title: "Delete or report the text if it is clearly fake", body: ["Once you know it is a scam, remove it so you do not click it later by mistake."] },
    ],
    tips: ["Package-delivery and unpaid-toll scams are common because they look routine."],
    warnings: ["Do not answer questions or confirm personal details in a suspicious text thread."],
    fallback: { title: "If this did not work", body: "If you already tapped a link or shared information, move to the emergency or fake-site recovery guide.", actions: ["Change any password you entered.", "Watch payment accounts closely if card details were involved."] },
    relatedGuides: ["what-to-do-after-entering-a-password-on-a-fake-site", "clicked-something-suspicious-right-now"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["text message scam", "is this text real", "phishing sms"],
    media: { heroImage: guideHeroPlaceholder("text scam guide") },
  },
  {
    title: "Turn off scam browser notifications",
    slug: "turn-off-scam-browser-notifications",
    category: "safety-scams",
    summary: "Remove unwanted browser notification permissions when scammy alerts keep showing up on the screen.",
    whatThisFixes: ["Suspicious browser notifications keep appearing.", "A website was allowed to send alerts and now abuses that permission."],
    symptoms: ["Fake security messages appear as system-like alerts.", "The browser keeps showing strange promotions or warnings."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Soon",
    beforeYouStart: ["Notice which browser the notifications are coming from if you can."],
    steps: [
      { title: "Open the browser notification settings", body: ["This is the fastest safe place to remove a bad site permission."], image: screenshotPlaceholder("browser notification site permissions") },
      { title: "Find the noisy or suspicious site", body: ["The site name often looks unfamiliar or slightly off."] },
      { title: "Block or remove the site permission", body: ["That stops the alerts instead of just dismissing them."] },
      { title: "Restart the browser and confirm the alerts stop", body: ["A clean restart helps the new settings take effect."] },
    ],
    tips: ["If you do not recognize a site at all, remove its permission."],
    warnings: ["Do not click the notifications while you are trying to stop them."],
    fallback: { title: "If this did not work", body: "The alerts may come from another browser or from the operating system notification list.", actions: ["Check another installed browser.", "Use the browser pop-up guide next."] },
    relatedGuides: ["stop-browser-pop-ups", "identify-a-suspicious-pop-up"],
    featured: false,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["browser notification scam", "stop fake browser alerts", "remove scam notifications"],
    media: { heroImage: guideHeroPlaceholder("browser notification scam guide") },
  },
];
