import type { Guide } from "@/types/content";

import { guideHeroPlaceholder, screenshotPlaceholder } from "./helpers";

export const wifiAndInternetGuides: Guide[] = [
  {
    title: "Wi-Fi password is not working",
    slug: "wifi-password-is-not-working",
    category: "wifi-internet",
    summary: "Check the password basics first when the network name is right but the device still refuses to connect.",
    whatThisFixes: ["The Wi-Fi password keeps being rejected.", "You are stuck on a login screen even though the network is visible."],
    symptoms: ["The device says incorrect password.", "Other devices may connect while one does not.", "The password may have changed."],
    difficulty: "Easy",
    estimatedTimeMinutes: 7,
    urgency: "Soon",
    beforeYouStart: ["Confirm the network name carefully.", "Check for capital letters, symbols, and spaces in the password."],
    steps: [
      { title: "Forget the saved network and start fresh", body: ["Old saved credentials can keep causing failed attempts."], image: screenshotPlaceholder("forget Wi-Fi network screen") },
      { title: "Enter the password slowly", body: ["Show the password on screen if the device allows it so you can spot mistakes."] },
      { title: "Test another device if possible", body: ["That tells you whether the problem is one device or the whole network."] },
      { title: "Ask whether the router password was changed recently", body: ["The saved password may simply be outdated."] },
    ],
    tips: ["Some routers have a label with the original Wi-Fi password, but it may not match if someone changed it later."],
    warnings: ["Do not keep guessing so many times that you lock yourself out of a portal or support process."],
    fallback: { title: "If this did not work", body: "The network may use a different password, portal, or device restriction.", actions: ["Restart the router once if you control it.", "Ask the network owner for the current password."] },
    relatedGuides: ["reconnect-to-wi-fi", "restart-a-router-safely"],
    featured: false,
    commonFix: true,
    emergencyRelevant: false,
    searchAliases: ["wifi password wrong", "cannot join wifi", "incorrect wifi password"],
    media: { heroImage: guideHeroPlaceholder("Wi-Fi password guide") },
  },
  {
    title: "Restart a router safely",
    slug: "restart-a-router-safely",
    category: "wifi-internet",
    summary: "Restart the router without factory-resetting it or accidentally making the problem worse.",
    whatThisFixes: ["Multiple devices lost internet.", "The router seems stuck or unresponsive."],
    symptoms: ["The connection drops everywhere.", "Router lights look unusual or frozen.", "Restarting is the next safe step."],
    difficulty: "Easy",
    estimatedTimeMinutes: 5,
    urgency: "Soon",
    beforeYouStart: ["Tell other people on the network if they are currently using it.", "Find the power cable, not the reset pin."],
    steps: [
      { title: "Unplug the power cable from the router", body: ["Do not press a reset button or hold any tiny recessed pin."] },
      { title: "Wait about 20 seconds", body: ["This gives the router time to fully power down."] },
      { title: "Plug it back in and wait a few minutes", body: ["Routers often need longer than expected to come back online."], image: screenshotPlaceholder("router lights after restart") },
      { title: "Reconnect one device and test a simple website", body: ["That confirms whether the restart solved the connection problem."] },
    ],
    tips: ["If there is a separate modem, restart only what you understand and one device at a time."],
    warnings: ["A factory reset can erase custom network names and passwords, so avoid it unless you intend to reconfigure everything."],
    fallback: { title: "If this did not work", body: "The issue may be with the internet provider, cabling, or the router itself.", actions: ["Check whether your provider reports an outage.", "Try the connected-but-nothing-loads guide next."] },
    relatedGuides: ["reconnect-to-wi-fi", "wifi-password-is-not-working"],
    featured: true,
    commonFix: true,
    emergencyRelevant: true,
    searchAliases: ["restart router", "reboot router safely", "internet router reset without factory reset"],
    media: { heroImage: guideHeroPlaceholder("router restart guide") },
  },
  {
    title: "Internet is slow on Windows",
    slug: "internet-is-slow-on-windows",
    category: "wifi-internet",
    summary: "Check the quick Windows-side causes first when the connection technically works but feels unusually slow.",
    whatThisFixes: ["Pages load very slowly on a Windows laptop.", "Downloads or video calls lag more than usual."],
    symptoms: ["One Windows device is slow while others seem okay.", "The Wi-Fi stays connected but performance is poor."],
    difficulty: "Easy",
    estimatedTimeMinutes: 9,
    urgency: "Soon",
    beforeYouStart: ["Close large downloads if one is already running.", "Stay near the router if you can."],
    steps: [
      { title: "Restart the browser or app that feels slow", body: ["This separates an app problem from a broader connection problem."] },
      { title: "Pause cloud backups, downloads, or updates", body: ["One background transfer can make the whole connection feel worse."] },
      { title: "Reconnect to Wi-Fi or restart the laptop", body: ["A fresh connection often helps if Windows got stuck with a weak session."], image: screenshotPlaceholder("Windows Wi-Fi quick settings") },
      { title: "Run a simple speed test only after the basics", body: ["That helps confirm whether the slowdown is real or limited to one app."] },
    ],
    tips: ["If video calls are the main problem, closing unused tabs helps more than people expect."],
    warnings: ["Do not install network booster tools from random websites."],
    fallback: { title: "If this did not work", body: "The slowdown may be router-wide or provider-wide.", actions: ["Try the router restart guide.", "Compare with another device on the same network."] },
    relatedGuides: ["reconnect-to-wi-fi", "restart-a-router-safely"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["windows internet slow", "pc wifi slow", "slow connection on windows"],
    media: { heroImage: guideHeroPlaceholder("slow internet on Windows guide") },
  },
  {
    title: "Internet is slow on a Mac",
    slug: "internet-is-slow-on-a-mac",
    category: "wifi-internet",
    summary: "Use the quick Mac-side checks first when websites, calls, or downloads feel slower than they should.",
    whatThisFixes: ["The Mac is online but feels slow on the web.", "Only the Mac seems slower than the other devices."],
    symptoms: ["Pages take a long time to open.", "Video calls stutter.", "Downloads crawl more than expected."],
    difficulty: "Easy",
    estimatedTimeMinutes: 9,
    urgency: "Soon",
    beforeYouStart: ["Close any large downloads first.", "Stay close to the router if you can."],
    steps: [
      { title: "Close the app or browser tab that feels slow", body: ["This tells you whether one app is overloaded or the whole connection is affected."] },
      { title: "Reconnect to Wi-Fi from the menu bar or settings", body: ["That refreshes the connection without doing anything risky."], image: screenshotPlaceholder("macOS Wi-Fi menu") },
      { title: "Restart the Mac if the slowdown feels system-wide", body: ["That clears a stuck background process or stale connection."] },
      { title: "Test one simple site and one simple app", body: ["Checking two things keeps you from chasing the wrong problem."] },
    ],
    tips: ["If Safari is slow but another browser is fine, the browser may be the real issue."],
    warnings: ["Do not change advanced DNS or router settings unless you know why you are changing them."],
    fallback: { title: "If this did not work", body: "The problem may be with the router or provider, not the Mac alone.", actions: ["Try the router restart guide.", "Compare with another device on the same Wi-Fi."] },
    relatedGuides: ["reconnect-to-wi-fi", "restart-a-router-safely"],
    featured: false,
    commonFix: false,
    emergencyRelevant: false,
    searchAliases: ["mac internet slow", "macbook wifi slow", "slow internet on mac"],
    media: { heroImage: guideHeroPlaceholder("slow internet on Mac guide") },
  },
];
